kind: pipeline
type: docker
name: Check messasges.po

steps:
  - name: Run default Xgettext
    image: friendicaci/transifex
    commands:
      - ./bin/run_xgettext.sh

  - name: Check default
    image: friendicaci/transifex
    commands:
      - /check-messages.sh