---
language: php
## Friendica supports PHP version >= 5.6
php:
 - 5.6
 - 7.0
 - 7.1
 - 7.2

services:
 - mysql
env:
 - MYSQL_HOST=localhost MYSQL_PORT=3306 MYSQL_USERNAME=travis MYSQL_PASSWORD= MYSQL_DATABASE=test

install:
 - composer install
before_script:
 - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
