name: Lint
on: pull_request

jobs:
  php-cs-fixer:
    name: php-cs check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        uses: jitterbit/get-changed-files@v1
      - name: Set up php
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.2
          coverage: none
      - name: Install dependencies
        run: bin/composer.phar run cs:install
      - name: Run coding standards check
        run: |
          if ! echo "${{ steps.changes.outputs.added }}" | grep -qE "^(\\.php_cs(\\.dist)?|composer\\.lock)$"; then EXTRA_ARGS=$(printf -- '--path-mode=intersection\n--\n%s' "${{ steps.changes.outputs.added }}"); else EXTRA_ARGS=''; fi
          bin/dev/php-cs-fixer/vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --diff --diff-format=udiff --dry-run --stop-on-violation --using-cache=no ${EXTRA_ARGS}
        shell: bash